### PR TITLE
Add --skip-in-use Option

### PR DESCRIPTION
**Pull request by waynerobinson**
Skips deleting snapshots where it is in use by an Amazon Machine Image
(AMI) rather than raising an error.

Fixes alestic/ec2-expire-snapshots#3

### CODE REVIEW

**Comment by waynerobinson** [comment]
Perl is far from my first language so I apologise for the quality of the code in this PR. Hope it helps, it works well for us in our production environment.

**Comment by ehammond** [comment]
Thanks for doing the work and for submitting this.

I don't think we need to make it as complicated as an option. I would like to see it simply skip any snapshot that is in use with an informational message like the one you list.

**Comment by ehammond** [comment]
and feel free to pester me by email if I'm not responsive on GitHub.

**Comment by ehammond** [comment]
Thanks again for working on this.

I'm moving in the direction of #24 which is a simplification without requiring specifying an option.

**Pull request closed without merging**
