### PR TITLE
Find by filter

### PR DESCRIPTION
**Pull request by bmo**
Search by AWS filter criteria vs. volume id

### CODE REVIEW

**Comment by ehammond** [comment]
Thank you for working on this and for submitting the pull request.

I can see the power of being able to use filters to select snapshots, but I am not comfortable with how easy it is to misunderstand the meaning of this functionality and the potential for unrecoverable disaster.

For example, if no filter is provided the docs say that this selects all snapshots. If a user wanted to save the first snapshot of each month and provided no filter, it would only save the first snapshot of the month across their entire account and across all volumes. This could easily delete all snapshots of almost all volumes in their account, because all snapshots would be treated as part of the same "series".

I know there is an issue where multiple volumes are logically the same data to be expired (e.g., database file system keeps getting moved to a larger volume based on a snapshot of the previous). It would be nice if there was a better solution for that case that didn't have the catastrophic potential of a global snapshot filter. It would be nice if EBS made it easy to see a volume ancestry so that you could delete snapshots of vol-X and all of its ancestors.

Maybe I'm just being paranoid, pessimistic, and overcautious, but the risk of mistakes seem high and the consequences devastating.

**Comment by neurogenesis** [comment]
Snapshots have metadata about the volume they were created from, and volumes likewise have the snapshot if created from a restore.

Using a graphing lib like graphviz, you can visually model the ancestry. It helps immensely when trying to identify entire trees or branches that can be pruned.

Doing that programmatically without understanding what the tree looks like is most certainly dangerous. You would have to have a complex rule parser that allows rules to be applied to subsets of the larger graph. For example, it's ok to delete all snapshots and volumes that are descendants of volume A, but for volume B: any snapshot past an expiration date or any snapshot whose parent volume is unused / unattached.

That seems well beyond the scope of the current tool.

**Comment by ehammond** [comment]
I would have less of a problem with letting the user specify an arbitrary filter rule if that filter were applied for snapshots of each volume being expired instead of across all volumes (though this does in some ways make the program have multiple filtering passes instead of one and the inconsistency would probably cause too much confusion for me).

My main concern with the current proposed change is that users will think it works within the volume framework. In fact, the submitter of pull request #25 appears to have assumed just that.

I know this isn't the use case being addressed with the more powerful option proposed here. It isn't a bad feature; it's just a personal judgement that I'm not comfortable releasing it.

Thanks again for creating the feature and for making it publicly available. Folks are welcome to use it if it solves their needs. If enough people find it useful and we can figure out a way to make it safer, perhaps we can revisit this in the future.

**Comment by markstos** [comment]
I agree with @ehammond I tried another tool that I assumed it was keeping the "30 most recent snapshots" per-volume, when it was really applying globally and keeping only the "30 most recent snapshots across all volumes", which I can hardly see a use for. I ended up deleting about 10x more backups than I expected.  

Keeping snapshot rotation/deletion to be per-volume I matches the common expectation.

**Pull request closed without merging**
